#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Tags: very-slow

# NOTE: msa-list-filtered is the authoritative file,
#   everything else may not be filtered.

set -e
set -u

source ./api/pipeline.sh


CONVERT_FASTA_TO_TAB=./opt/misc-bioinfo-scripts/convert-fasta-to-tab
FILTER_CDD_SCRIPT=$0-scripts/filter-cdd.R

# Limited by the fact that we need to be able to add 5% random sequences
# by adding 1 sequence
MIN_MSA_NUMSEQ=19
MAX_MSA_NUMSEQ=200 # Otherwise things become too slow

# Limited by the length diversity of 2011 Uniport
## for each individual length Uniprot must provide 1000+ unique proteins
MIN_MSA_AVR_SEQLEN=8
MAX_MSA_AVR_SEQLEN=1000

# Limited by the 2011 speed on MSA aligners
MAX_MSA_RESIDUES=100000 # 100k


EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)
DATA_IN_EXTRACTED="./$EXPERIMENT_NAME/002-start-data-out/cdd-extracted"
DATA_OUT="./$EXPERIMENT_NAME/$0-data-out"

mkdir -p $DATA_OUT 2> /dev/null && true


function callback {
    mkdir -p $DATA_OUT/all-alignments-tab{,-new} 2> /dev/null && true
    
    ls $DATA_IN_EXTRACTED | 
      while read i; do
        cat $DATA_IN_EXTRACTED/$i |
          $CONVERT_FASTA_TO_TAB |
          egrep -v "^lcl[|]consensus" |   # Filter out consensus sequences
          cat > $DATA_OUT/all-alignments-tab-new/$i.tab
      done
    rm -rf $DATA_OUT/all-alignments-tab
    mv $DATA_OUT/all-alignments-tab{-new,}
}
upstream_done_time_prefix=$DATA_IN_EXTRACTED
done_time_prefix=$DATA_OUT/all-alignments-tab
pipeline   $upstream_done_time_prefix   $done_time_prefix \
  "Doing reshape from $DATA_IN_EXTRACTED to $DATA_OUT/all-alignments-tab" \
  callback # 14 min




function callback {
  echo "Generating the unfiltered msa-list"
  ls -1 $DATA_OUT/all-alignments-tab/ > $DATA_OUT/msa-list-new
  mv $DATA_OUT/msa-list{-new,}

  echo "Counting numbers of sequences in the unfiltered msa-list"
  cat $DATA_OUT/msa-list |
    while read i; do
      cat $DATA_OUT/all-alignments-tab/$i | wc -l | tr "\n" "\t"
      echo $i
    done > $DATA_OUT/msa-sizes-numseq-new
  mv $DATA_OUT/msa-sizes-numseq-new $DATA_OUT/msa-sizes-numseq
}
upstream_done_time_prefix=$done_time_prefix
done_time_prefix=$DATA_OUT/msa-sizes-numseq
pipeline   $upstream_done_time_prefix   $done_time_prefix \
  "Getting msa-{list,sizes-numseq} of $DATA_OUT/all-alignments-tab" \
  callback # 5 min





function callback {
  #  <all_alignments_dir> directory will all MSAs in tab format
  #  <msa_numseq_file>    file that lists all MSAs + their NumSeq size
  #
  #  <max_msa_residues>   maximum number of residues (non-gap) in MSA
  #  <min_msa_avr_seqlen> minimum average sequence length in MSA
  #  <max_msa_avr_seqlen> maximum -//-
  #  <min_msa_numseq>     minimum number of sequences (NumSeq) in MSA
  $FILTER_CDD_SCRIPT \
    $DATA_OUT/all-alignments-tab \
    $DATA_OUT/msa-sizes-numseq \
    \
    $MAX_MSA_RESIDUES \
    $MIN_MSA_AVR_SEQLEN \
    $MAX_MSA_AVR_SEQLEN \
    $MIN_MSA_NUMSEQ \
    > $DATA_OUT/msa-list-filtered-new
    
    #$MAX_MSA_NUMSEQ \

  # Commit
  mv $DATA_OUT/msa-list-filtered{-new,}

  # Cleanup (all of this info is already in msa-list-filtered
  rm $DATA_OUT/msa-sizes-length-trimmed 
  rm $DATA_OUT/msa-sizes-length
  rm $DATA_OUT/msa-sizes-numseq
}
upstream_done_time_prefix=$done_time_prefix
done_time_prefix=$DATA_OUT/msa-list-filtered
pipeline   $upstream_done_time_prefix   $done_time_prefix \
  "Filtering MSAs from $DATA_OUT/all-alignments-tab to 
   $DATA_OUT/msa-list-filtered" \
  callback # 4 min
