#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Tags: very-slow

set -e
set -u

source ./api/pipeline.sh


CONVERT_FASTA_TO_TAB=./opt/misc-bioinfo-scripts/convert-fasta-to-tab

MIN_SEQ_LENGTH=8     # below this there are much less than 1000 seqs per length
MAX_SEQ_LENGTH=1000  # above this there are less seqs than per a given length



EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)

UNIPROT_EXTRACTED="./$EXPERIMENT_NAME/002-start-data-out/uniprot-extracted"

DATA_OUT="./$EXPERIMENT_NAME/$0-data-out"
DATA_OUT_UNIPROT="$DATA_OUT/uniprot"

mkdir -p $DATA_OUT_UNIPROT 2> /dev/null && true



# Uniprot

function callback {
  mkdir -p $DATA_OUT_UNIPROT-new 2> /dev/null && true
    cat $UNIPROT_EXTRACTED/uniprot_{sprot,trembl}.fasta |
      $CONVERT_FASTA_TO_TAB | cut -s -f 2 |
      while read one_protein; do
        seq_len=${#one_protein}

        # Filer for the length criteria
        if [ $seq_len -ge $MIN_SEQ_LENGTH ] &&
          [ $seq_len -le $MAX_SEQ_LENGTH ]; then
            seq_len_padded=`printf "%04d" $seq_len`
            echo $one_protein >> \
              $DATA_OUT_UNIPROT-new/length$seq_len_padded-tab
        fi
      done

  # Dedup
  ls $DATA_OUT_UNIPROT-new/length*-tab | while read tab_file; do
    sort $tab_file | uniq > $tab_file-new
    mv $tab_file{-new,}
  done

  rm -rf $DATA_OUT_UNIPROT
  mv $DATA_OUT_UNIPROT{-new,}
}
upstream_done_time_prefix="$UNIPROT_EXTRACTED/uniprot_trembl.fasta"
done_time_prefix=$DATA_OUT_UNIPROT
pipeline   $upstream_done_time_prefix   $done_time_prefix \
  "Doing a reshape from $UNIPROT_EXTRACTED to $DATA_OUT_UNIPROT" \
  callback # 7.6 hours
