#!/bin/bash

source ./api/pipeline.sh
set -e
set -u

# Tags: takes-optional-arguments
 
if [ $# != 2 ] && [ $# != 3 ]; then
  echo "Usage: $0 <sample-size> <number-of-samples>   [-s]" >&2
  echo "" >&2
  echo "  <sample-size>        how many alignments should be in 1 sample" >&2
  echo "  <number-of-samples>  how many samples should be taken" >&2
  echo "" >&2
  echo "  -f                   force always runing, never skip any steps" >&2
  exit 1
fi

# Arguments
SAMPLE_SIZE=$1                              # sample size (mandatory)
N=$2                                        # number of samples (mandatory)
set +u
[ "$3" == '-f' ] && export ALWAYS_RUN=true  # skip steps (optional)
[ -n "$3" ] && [ "$3" != '-f' ] && (echo "Invalid option $3"; exit 1)
set -u

DATA_IN="$0-data-in"
DATA_OUT="$0-data-out"

mkdir -p $DATA_IN $DATA_OUT 2> /dev/null && true



function callback {
    echo "Importing (few files) 005-reshape-data-out/msa-*"
    cp ./005-reshape-data-out/msa-* $DATA_IN/
}
parrent_done_time_prefix="./005-reshape-data-out"
done_time_prefix=$DATA_IN
pipeline   $parrent_done_time_prefix   $done_time_prefix \
  "Importing data into $DATA_IN" callback



for seed in `seq $N`; do
  sample_name="sample-size$SAMPLE_SIZE-id$seed-list"
  function callback {
    $0-scripts/sample.R $seed $SAMPLE_SIZE $DATA_IN/msa-list > \
      "$DATA_OUT/$sample_name"
  }
  
  parrent_done_time_prefix=$done_time_prefix
  done_time_prefix="$DATA_OUT/$sample_name"
  pipeline   $parrent_done_time_prefix   $done_time_prefix \
    "Sample $sample_name from $DATA_IN/msa-list" \
    callback
done
