#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


source ./api/pipeline.sh
set -e
set -u

# Tags: takes-optional-arguments

SAMPLING_SCRIPT=$0-scripts/sample.R
SAMPLING_SCRIPT2=$0-scripts/sample-groups-with-.5identiy-same-sample.R


MSA_DIMENTIONS_SCRIPT=$0-scripts/msa-dimentions.rb
 
if [ $# != 2 ] && [ $# != 3 ]; then
  echo "Usage: $0 <sample-size> <number-of-samples>   [-s]" >&2
  echo "" >&2
  echo "  <sample-size>        how many alignments should be in 1 sample" >&2
  echo "  <number-of-samples>  how many samples should be taken" >&2
  echo "" >&2
  echo "  -f                   force always runing, never skip any steps" >&2
  exit 1
fi

# Arguments
SAMPLE_SIZE=$1                              # sample size (mandatory)
N=$2                                        # number of samples (mandatory)
set +u
[ "$3" == '-f' ] && export ALWAYS_RUN=true  # skip steps (optional)
[ -n "$3" ] && [ "$3" != '-f' ] && (echo "Invalid option $3"; exit 1)
set -u

EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)


UPSTREAM_DATA="./$EXPERIMENT_NAME/004-reshape-cdd-data-out"

DATA_IN="./$EXPERIMENT_NAME/$0-data-in"
DATA_OUT="./$EXPERIMENT_NAME/$0-data-out"

mkdir -p $DATA_IN $DATA_OUT 2> /dev/null && true


function callback {
    echo "Importing (few files) $UPSTREAM_DATA/msa-*"
    cp "$UPSTREAM_DATA/msa-"* $DATA_IN/
}
upstream_done_time_prefix=$UPSTREAM_DATA/msa-list-filtered
done_time_prefix=$DATA_IN
pipeline   $upstream_done_time_prefix   $done_time_prefix \
  "Importing data into $DATA_IN" callback


# Normal Random Sampling
for seed in `seq $N`; do
  sample_list="sample-size$SAMPLE_SIZE-id$seed-list"
  function callback {
    $SAMPLING_SCRIPT $seed $SAMPLE_SIZE $DATA_IN/msa-list-filtered > \
      "$DATA_OUT/$sample_list"

    mkdir -p "$DATA_OUT/$sample_list-tab-new" 2> /dev/null && true
    cat "$DATA_OUT/$sample_list" | while read msa_line; do
      msa_tab_filename=$(printf "$msa_line" | awk '{print $1}')
      cp "$UPSTREAM_DATA/all-alignments-tab/$msa_tab_filename" \
        "$DATA_OUT/$sample_list-tab-new"
    done
    rm -rf "$DATA_OUT/$sample_list-tab"
    mv "$DATA_OUT/$sample_list-tab"{-new,}
  }
  
  upstream_done_time_prefix=$done_time_prefix
  done_time_prefix="$DATA_OUT/$sample_list-tab"
  pipeline   $upstream_done_time_prefix   $done_time_prefix \
    "Sample $sample_list from $DATA_IN/msa-list-filtered" \
    callback
done



# Sampling with fishing and extracting seqeunce groups with 50% identity
for seed in `seq $N`; do
  upstream="sample-size$SAMPLE_SIZE-id$seed-list"
  sample_list="sample-size$SAMPLE_SIZE-id50$seed-list"
  function callback {
    mkdir -p "$DATA_OUT/$sample_list-tab-new" 2> /dev/null && true

    $SAMPLING_SCRIPT2 \
      $DATA_OUT/$upstream \
      $UPSTREAM_DATA/all-alignments-tab/ \
     > \
      "$DATA_OUT/$sample_list-tab-new/raw"

    cat "$DATA_OUT/$sample_list-tab-new/raw" | $MSA_DIMENTIONS_SCRIPT \
    > "$DATA_OUT/$sample_list"

    cat "$DATA_OUT/$sample_list-tab-new/raw" | ruby -e "
      open_files = {}
      while line = STDIN.gets
        msa_name, seq_id, seq = line.split(\"\\t\")
        open_files[msa_name] = \
          File.open(\"$DATA_OUT/$sample_list-tab-new/#{msa_name}\",'w') if
            !open_files.keys.include?(msa_name)
        open_files[msa_name].puts \"#{seq_id}\\t#{seq}\"
      end
    "
    
    rm -rf "$DATA_OUT/$sample_list-tab"
    mv "$DATA_OUT/$sample_list-tab"{-new,}
  }
  
  upstream_done_time_prefix=$done_time_prefix
  done_time_prefix="$DATA_OUT/$sample_list-tab"
  pipeline   $upstream_done_time_prefix   $done_time_prefix \
    "Sample $sample_list from $DATA_IN/msa-list-filtered" \
    callback
done
