#!/bin/bash

source ./api/pipeline.sh
set -e
set -u

# Tags: slow-import

IN_DIR="$0-data-in"
OUT_DIR="$0-data-out"

mkdir -p $IN_DIR $OUT_DIR 2> /dev/null && true

(cd 008-sample-data-out/; ls -1 --indicator-style=none sample*-list) |
while read sample
do
  function cb {
      mkdir -p "$IN_DIR/$sample"{,-new} 2> /dev/null && true
      cat "008-sample-data-out/$sample" | sed 's/.tab$//' | while read file_name; do
        cp "005-reshape-data-in/fasta.tar.gz-extracted/$file_name" \
          "$IN_DIR/$sample-new/"
      done
      rm -rf "$IN_DIR/$sample"
      mv "$IN_DIR/$sample"{-new,}
  }
  parrent_done_time_prefix="008-sample-data-out/$sample"
  done_time_prefix="$IN_DIR/$sample"
  pipeline   $parrent_done_time_prefix   $done_time_prefix \
    "Importing 008-sample-data-out/$sample-list items \
     from 005-reshape-data-in/fasta.tar.gz-extracted" cb

done
