#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


source ./api/pipeline.sh
set -e
set -u

CONVERT_FASTA_TO_TAB=./opt/misc-bioinfo-scripts/convert-fasta-to-tab


# Tags:

if [ $# != 1 ] && [ $# != 2 ]; then
  echo "Usage: $0 <sample-size>  [-s]" >&2
  echo "" >&2
  echo "  <sample-size>        You may have several sizes of samples." >&2
  echo "                       Which size group do you whan scored?" >&2
  echo "" >&2
  echo "  -f                   force always runing, never skip any steps" >&2
  exit 1
fi

# Arguments
SAMPLE_SIZE=$1                              # sample size (mandatory)
set +u
[ "$2" == '-f' ] && export ALWAYS_RUN=true
[ -n "$2" ] && [ "$2" != '-f' ] && (echo "Invalid option $2"; exit 1)
set -u


EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)
UPSTREAM_DIR="./$EXPERIMENT_NAME/010-run-guidance-data-out/sample-size$SAMPLE_SIZE-id*-list-tab-rand*-tab-nogaps"

ls -d $UPSTREAM_DIR/*.tab | while read guidance_out_dir; do
  cat $guidance_out_dir/MSA.MAFFT.aln.With_Names | $CONVERT_FASTA_TO_TAB \
    > $guidance_out_dir/MSA.MAFFT.aln.With_Names-tab
done


