#!/bin/bash

set -e
set -u

DATA_OUT="$0-data-out"
mkdir -p $DATA_OUT-new 2> /dev/null && true


grep "MEAN_RES_PAIR_SCORE" \
  010-run-guidance-data-out/sample*-list-nogaps/*/MSA.MAFFT.Guidance_msa.scr |
  while read line; do

    sample=`echo $line |
     awk -F"/" '{print $2}' | # Parse directory structure
     awk -F- '{print $1 "-" $2 "-" $3}' # Parse file name structure
    `

    echo $line |
      awk '{print $1, $4}' | # $2 is MEAN_RES_PAIR_SCORE, $4 is MEAN_COL_SCORE
      awk -F/ '{print $3, $4}' |
      awk '{print $1 "\t" $3}' |
      cat >> $DATA_OUT-new/$sample-mafft-guidance-msa-scr

   done

for i in $DATA_OUT-new/*-mafft-guidance-msa-scr; do
  sort -nk 2 $i > $i-new
  mv $i{-new,}
done


# Danger Zone
rm -rf $DATA_OUT

# Done
mv $DATA_OUT{-new,}
