#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


source ./api/pipeline.sh
set -e
set -u

# Tags: depends-on-ruby-scripts

SAMPLE_UNIPROT="$0-scripts/sample-uniprot"
UNIPROT_TAB="./data/uniprot_2011_02.tab"

# Get average sequence length of samples
# ?
min_size=1
max_size=1000


# Pull out random sequences
sample_size=4
sample_id=1
random_seqs=`$SAMPLE_UNIPROT \
  $min_size $max_size \
  $sample_size $sample_id \
  $UNIPROT_TAB`


# Add sequences to alignment samples
samples=`echo 010-run-guidance-data-in/sample-*-list-nogaps`
# TODO: Write to your own output directory?
for s in $samples; do
  for family_fasta_file in `echo $s/*FASTA`; do
    cp $family_fasta_file{,-with-random}
    count=1
    for rs in $random_seqs; do
      echo ">RAND$count" >> $family_fasta_file-with-random
      echo $rs >> $family_fasta_file-with-random
      count=$((count+1)) 
    done
  done
done
