#!/bin/bash

source ./api/pipeline.sh
set -e
set -u

# Tags: depends-on-ruby-scripts

SAMPLE_UNIPROT="$0-scripts/sample-uniprot"
UNIPROT_TAB="./data/uniprot_2011_02.tab"

# Get average sequence length of samples
# ?
min_size=1
max_size=1000


# Pull out random sequences
sample_size=4
sample_id=1
random_seqs=`$SAMPLE_UNIPROT \
  $min_size $max_size \
  $sample_size $sample_id \
  $UNIPROT_TAB`


# Add sequences to alignment samples
samples=`echo 010-run-guidance-data-in/sample-*-list-nogaps`
# TODO: Write to your own output directory?
for s in $samples; do
  for family_fasta_file in `echo $s/*FASTA`; do
    cp $family_fasta_file{,-with-random}
    count=1
    for rs in $random_seqs; do
      echo ">RAND$count" >> $family_fasta_file-with-random
      echo $rs >> $family_fasta_file-with-random
      count=$((count+1)) 
    done
  done
done
