#!/usr/bin/env Rscript

score.files <<- dir("014-get-scores-data-out", full.names=T)

tables <- lapply(score.files, read.table)
scores <- lapply(tables, function(x) {x$V2})

# merge(tables[[1]], tables[[2]], by="V1")

dir.create("024-box-plot-data-out", showWarnings=F)
png("024-box-plot-data-out/5-samples-of-size100.png")
boxplot(scores, ylab="GUIDANCE score")
dev.off()
