#!/usr/bin/env Rscript

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


scrs.list <- lapply(dir("101-scores-original", full.names=T), read.table)
scrs.list.rand <-
  lapply(dir("102-scores-with-random", full.names=T), read.table)
#scores <- lapply(tables, function(x) {x$V2})


for (i in 1:length(scrs.list)) {
  set1 <- scrs.list[[i]]$V2
  set2 <- scrs.list.rand[[i]]$V2

  #print(c(mean(set1), mean(set2)))
  dir.create("024-box-plot-data-out", showWarnings=F)
  png(paste("024-box-plot-data-out/sample-", i, ".png", sep=""))
  boxplot(list(set1, set2), ylab="GUIDANCE Score")
  title(paste("Sample-", i, " (", 
  sprintf("%.3f", mean(set1)), ", ", 
  sprintf("%.3f", mean(set2)), ")", sep=""))
  dev.off()
}

# merge(tables[[1]], tables[[2]], by="V1")

