#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -u

source ./api/pipeline.sh

NORMD="./opt/norMD1_3/normd"

EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)
UPSTREAM="./$EXPERIMENT_NAME/010-run-guidance-data-out"
DATA_OUT="./$EXPERIMENT_NAME/$0-data-out"

mkdir -p $DATA_OUT 2> /dev/null && true

ls $UPSTREAM/sample-size100-id*-list-tab-rand*nogaps/*.FASTA.tab/MSA.MAFFT.aln.With_Names | while read msa; do
  echo "cd `pwd`; $NORMD $msa > $msa-normd"
  #$NORMD $msa 
done #> $DATA_OUT/all-scores
