#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -u

source ./api/pipeline.sh

SAMPLE_SIZE=100
NUM_THRESHOLDS=100
RAND_AMOUNT=0.05

# Tags: takes-optional-arguments

if [ $# != 3 ]; then
  echo "Usage: $0 <sample-size> <num-thresholds> <rand-amount>" >&2
  echo "" >&2
  echo "  <sample-size>        You may have several sizes of samples." >&2
  echo "                       Which size group do you whan scored?" >&2
  echo "  <num-thresholds>      " >&2 
  echo "  <rand-ammount>        " >&2 
  echo "" >&2
  exit 1
fi

EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)
UPSTREAM_DIR="./$EXPERIMENT_NAME/010-run-guidance-data-out"

GUIDANCE_RUN_TEMPLATE="$0-scripts/guidance-run.sh.template"

DATA_IN="./$EXPERIMENT_NAME/$0-data-in"
DATA_OUT="./$EXPERIMENT_NAME/$0-data-out"
mkdir -p $DATA_IN $DATA_OUT 2> /dev/null && true

SCORE_FILE="MSA.MAFFT.Guidance_res_pair_seq.scr_with_Names"

function callback {

  echo "Working..."

}

# Pick the latest done file
upstream_done_time_prefix=$(
  ls -t $UPSTREAM_DIR/sample-size$SAMPLE_SIZE-id*-list-tab-nogaps/*-done |
    head -n 1 | sed 's/-done$//'
)
done_time_prefix=$DATA_OUT
pipeline   $upstream_done_time_prefix   $done_time_prefix \
  "Classify all MSA alignments with the GUIDANCE per-seq seq_res_pair score" \
  callback
