#!/bin/bash

# UNNAMED is a classifier of outlier sequences in multiple alignments
# Copyright (C) 2011  Aleksandr Levchuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -u

source ./api/pipeline.sh


# Tags: takes-optional-arguments

if [ $# != 2 ]; then
  echo "Usage: $0 <sample-size> <num-thresholds> <rand-amount>" >&2
  echo "" >&2
  echo "  <sample-size>        You may have several sizes of samples." >&2
  echo "                       Which size group do you whan scored?" >&2
  echo "  <rand-ammount>       E.g. 0.05 " >&2 
  echo "" >&2
  exit 1
fi

SAMPLE_SIZE=$1
RAND_AMOUNT=$2

EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)
UPSTREAM_DIR="./$EXPERIMENT_NAME/010-run-guidance-data-out"

GUIDANCE_RUN_TEMPLATE="$0-scripts/guidance-run.sh.template"

#DATA_IN="./$EXPERIMENT_NAME/$0-data-in"
DATA_OUT="./$EXPERIMENT_NAME/$0-data-out/rand$RAND_AMOUNT"
mkdir -p $DATA_OUT 2> /dev/null && true

SCORE_FILE="MSA.MAFFT.Guidance_res_pair_seq.scr_with_Names"

function callback {
  spec="sample-size$SAMPLE_SIZE-id*-list-tab-rand$RAND_AMOUNT-tab-nogaps"
  all_score_files=$(ls $UPSTREAM_DIR/$spec/*/$SCORE_FILE)

  for seq_scores_file in $all_score_files; do
    sample_id=$(printf "$seq_scores_file" | awk -F/ '{print $4}')
    #sample_id=$(expr "$sample_id_raw" : '.*id\([0-9]*\)') || (
    #echo "ERROR: Could not parse out sample id in \"$sample_id_raw\""; exit 1)
    msa_tab_filename=$(printf "$seq_scores_file" | awk -F/ '{print $5}')

    mkdir "$DATA_OUT/$sample_id" 2> /dev/null && true
    outfile="$DATA_OUT/$sample_id/$msa_tab_filename-res-pair-seq-scr"
    cat $seq_scores_file | grep -v SEQUENCE_NAME | grep -v "#END" > $outfile

    #outfile="$DATA_OUT/$sample_id/$msa_tab_filename-cutoffs"
    #cat /dev/null > $outfile
    #for t in `seq 0 $THRESHOLD_STEP 1`; do
    #  cat $seq_scores_file | grep -v SEQUENCE_NAME | grep -v "#END" | \
    #    ruby -ne "
    #      seq, score = \$_.split
    #      puts(seq + ':::' + score) if score.to_f > $t
    #    " | tr "\n" " " >> $outfile
    #  echo >> $outfile # End of the line
    #done
  done

}

# Pick the latest done file
upstream_done_time_prefix=$(
  ls -t $UPSTREAM_DIR/sample-size$SAMPLE_SIZE-id*-list-tab-nogaps/*-done |
    head -n 1 | sed 's/-done$//'
)
done_time_prefix=$DATA_OUT
pipeline   $upstream_done_time_prefix   $done_time_prefix \
  "Classify all MSA alignments with the GUIDANCE per-seq seq_res_pair score" \
  callback
