#!/usr/bin/env Rscript

sh <- function(cmd){lines <- readLines(p <- pipe(cmd)); close(p); lines}

SAMPLE_SIZE <- 100
RAND_AMOUNT <- 0.05
EXPERIMENT_NAME <- sh("ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2")

UPSTREAM_DIR <- paste(EXPERIMENT_NAME,
  "070-build-roc-classifer-data-out", sep="/")

OUT_DIR <- paste(EXPERIMENT_NAME, "071-plot-roc-out", sep="/")


library(ROCR)
dir.create(OUT_DIR, showWarnings=F)

load(paste(UPSTREAM_DIR, "predictions-guidance.Rdata"    , sep="/"))
load(paste(UPSTREAM_DIR, "predictions-normd-mod.Rdata"   , sep="/"))
load(paste(UPSTREAM_DIR, "predictions-normd-dx.Rdata"    , sep="/"))
load(paste(UPSTREAM_DIR, "predictions-normd-simple.Rdata", sep="/"))
load(paste(UPSTREAM_DIR, "predictions-normd-mod-dx.Rdata", sep="/"))

w_1 <-  4; c_1 <- 2;
w_2 <- 16; c_2 <- 9;
w_3 <-  8; c_3 <- 3;
w_4 <- 16; c_4 <- 8;
w_5 <-  2; c_5 <- 4;


png(paste(OUT_DIR, "roc.png", sep="/"),
   width = 750, height = 750, units = "px", type="cairo")

par(mar=c(5, 5, 2, 2))
par(cex.lab=2, cex.axis=1.5, font.main=12)

plot(performance(p_4,"tpr","fpr"), col=c_4, lwd=w_4)
plot(performance(p_2,"tpr","fpr"), col=c_2, lwd=w_2, add=T)
plot(performance(p_1,"tpr","fpr"), col=c_1, lwd=w_1, add=T)
plot(performance(p_3,"tpr","fpr"), col=c_3, lwd=w_3, add=T)
plot(performance(p_5,"tpr","fpr"), col=c_5, lwd=w_5, add=T)
axis(1, c())
axis(2, c(0, 1:10/10))
axis(3, c(0, 1:10/10))
box()

#grid(col="black") #lty=3, col="gray")
abline( v=0:20/20, h=0:20/20, lty=3, col="gray") 

leg.txt <- c(
  l_1,
  l_2 ,
  l_3
  ,l_4
  ,l_5
)

legend("bottomright", inset=0.037, leg.txt, 
  title="auc = area under the curve",
  col = c(c_1,c_2,c_3,c_4,c_5),
  lwd = c(w_1,w_2,w_3,w_4,w_5), cex=1.5)

dev.off()
