#!/usr/bin/env ruby

MIN_MAX_LENGTH = (ARGV[0].to_i)..(ARGV[1].to_i)
SAMPLE_SIZE = ARGV[2].to_i
SEED = ARGV[3].to_i
UNIPROT_TAB = ARGV[4]

srand(SEED)



# Pass 1: Count how many sequences meet length criterion
population_size = 
  File.open(UNIPROT_TAB).reduce(0) do |subtotal, line|
    seq = line.chomp.split("\t")[1]
    subtotal + (MIN_MAX_LENGTH.include?(seq.size) ? 1 : 0)
  end
linenumbers = (1..SAMPLE_SIZE).collect{1 + (rand * population_size).to_i}
STDERR.puts "Number of sequeces fit to length criterion: #{population_size}"
STDERR.puts ["Sample #{SAMPLE_SIZE} out of #{population_size}:"] +
  linenumbers + ["\n"]



# Pass 2: Extract sample
fit_seq_lineno = 0
File.open(UNIPROT_TAB) do |f|
  while line = f.gets
    seq = line.chomp.split("\t")[1]
    if MIN_MAX_LENGTH.include? seq.size
      fit_seq_lineno += 1
      puts seq if linenumbers.include? fit_seq_lineno
    end
  end

  raise "ERROR: Number of lines matching length criteria does not add up" if
    fit_seq_lineno != population_size
end
